name: Test

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test-work:
    runs-on: ubuntu-latest
    steps:
      - name: print date
        run: |
          echo hello $(date)
      
